name: Update tld
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-and-push-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Download file
      - name: TLD Alpha By Domain
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt'
          file-name: 'tlds-alpha-by-domain.txt'
          location: './output'
      # Commit
      - name: Commit Updates
        run: |
          if [ -z "$(git status --porcelain)" ]; then
              exit 0
            else
              git add .
              git config --local user.email "29797712+yuimatcha@users.noreply.github.com"
              git config --local user.name "yuimatcha"
              git commit -m "Update tld at $(date)" -a
            fi
      # Push to github
      - name: Push to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Generate tag dan push tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Push release dan kasih tag
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
